[package]
name = "network-discovery"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Network Peer Discovery"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
futures = "0.3.12"
once_cell = "1.7.2"
serde_yaml = "0.8.17"
tokio = { version = "1.8.1", features = ["full"] }

channel = {path = "../../crates/channel"}
bcs = "0.1.2"
event-notifications = { path = "../../state-sync/inter-component/event-notifications" }
aptos-config = { path = "../../config"}
aptos-crypto = {path = "../../crates/aptos-crypto"}
aptos-logger = {path = "../../crates/aptos-logger"}
aptos-metrics = {path = "../../crates/aptos-metrics"}
aptos-time-service = {path = "../../crates/aptos-time-service"}
aptos-secure-storage = { path = "../../secure/storage" }
aptos-types = {path = "../../types"}
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
network = {path = "../../network"}
short-hex-str = { path = "../../crates/short-hex-str" }

[dev-dependencies]
aptos-config = { path = "../../config", features = ["testing"]}
aptos-temppath = { path = "../../crates/aptos-temppath" }
netcore = { path = "../netcore", features = ["fuzzing"] }
rand = "0.8.3"
