[package]
name = "consensus-notifications"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
description = "The notification interface between state sync and consensus"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1" }

aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-types = { path = "../../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../../crates/aptos-workspace-hack" }

[dev-dependencies]
claim = "0.5.0"

move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
