[package]
name = "vm-validator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos vm validator"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
scratchpad = { path = "../storage/scratchpad" }
aptos-state-view = { path = "../storage/state-view" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptos-workspace-hack = { version = "0.1", path = "../crates/aptos-workspace-hack" }
executor = { path = "../execution/executor" }
storage-interface = { path = "../storage/storage-interface" }

[dev-dependencies]
rand = "0.8.3"

executor-test-helpers = { path = "../execution/executor-test-helpers" }
aptos-crypto = { path = "../crates/aptos-crypto", features = ["fuzzing"] }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../sdk/transaction-builder" }
aptos-types = { path = "../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptosdb = { path = "../storage/aptosdb", features = ["fuzzing"] }
vm-genesis = { path = "../aptos-move/vm-genesis" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["aptos-types/fuzzing", "aptos-crypto/fuzzing", "aptosdb/fuzzing"]
