[grcov.installer]
version = "0.8.2"

[system-tests]
smoke-test = { path = "smoke-test" }
testcases = { path = "testsuite/testcases" }

[cargo.sccache]
bucket = "ci-artifacts.aptoslabs.com"
prefix = "sccache/aptos/"
public = true
region = "us-west-2"
endpoint = "https://s3-us-west-2.amazonaws.com"
required-cargo-home = "/opt/cargo/"
required-git-home = "/opt/git/aptos-core"
envs = [
   #To debug sccache uncomment the two lines below.
   #["SCCACHE_ERROR_LOG","/tmp/sccache_log"],
   #["SCCACHE_LOG", "sccache::compiler::compiler=trace,rusoto_core::request=trace"],
]

[cargo.sccache.installer]
version = "0.2.16-alpha.0"
git = "https://github.com/mozilla/sccache.git"
git-rev = "ef50d87a58260c30767520045e242ccdbdb965af"
features = [ "s3" ]


[fix]

[clippy]
allowed = [
    # Deriving Arbitrary often causes this warning to show up.
    "clippy::unit_arg",
    "clippy::eval-order-dependence",
    "clippy::new-without-default",
    "clippy::rc_buffer",
    "clippy::upper_case_acronyms",
    "clippy::len-without-is-empty",
    "clippy::from-iter-instead-of-collect",
    "clippy::while-let-on-iterator",
    "clippy::bool-assert-comparison",
    "clippy::needless-collect",
    "clippy::enum-variant-names",
    "clippy::self-named-constructors",
]
warn = [
    "clippy::wildcard_dependencies",
]

[hakari]
resolver = "2"
hakari-package = "aptos-workspace-hack"
exact-versions = true
platforms = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
]

# Ideally we'd have powerpc-unknown-linux-gnu here as well, but unification causes openssl-sys to be included,
# and openssl can't be cross-compiled without extra work. This may need to be fixed in hakari through being able
# to say "consider only these packages for these target platforms".

[hakari.traversal-excludes]
workspace-members = [
    # Don't consider the crypto packages as they do weird things with mutually exclusive features.
    "aptos-crypto",
    "aptos-crypto-derive",

    # Also exclude the devtools packages since they get compiled with a different set of options.
    "x",
    "x-core",
    "x-lint",
]

[hakari.final-excludes]
third-party = [
    # Exclude the fail crate because the failpoints feature should only be enabled
    # for certain builds.
    { name = "fail" },
    { name = "move-binary-format", git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" },
    { name = "move-core-types", git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" },
    { name = "move-stdlib", git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" },
    { name = "move-vm-runtime", git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" },
    { name = "move-vm-types", git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" },
]

# This follows the same syntax as CargoOptionsSummary in guppy.
[summaries.default]
resolver = "2"
include-dev = false
initials-platform = "standard"

[summaries.default.target-platform]
triple = "x86_64-unknown-linux-gnu"
target-features = "all"

[summaries.default.host-platform]
triple = "x86_64-unknown-linux-gnu"
target-features = "all"

[summaries.default.omitted-packages]
workspace-members = [
    "aptos-workspace-hack",
]

[summaries.full]
version = "v2"
include-dev = true
initials-platform = "standard"
# Don't set target or host platforms, or omitted packages, for the full set.

[workspace]

# Regex for allowed characters in paths. Regex must have ^ and $ anchors.
allowed-paths = "^([a-zA-Z0-9._\\-/@:]|-)+$"

whitespace-exceptions = [
    ".github/actions/*/dist/*",
    # TODO: reevaluate skipping whitespace checks in .md files for the website
    "developer-docs-site/**/*",
    "**/*.exp",
    "**/*.errmap",
    "**/*.abi",
    "terraform/**/*",
]

license-exceptions = [
    "terraform/**/*",
]

[workspace.enforced-attributes]
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
license = "Apache-2.0"

[workspace.banned-deps.direct]
lazy_static = "use once_cell::sync::Lazy instead"

[workspace.banned-deps.default-build]
criterion = "criterion is only for benchmarks"
proptest = "proptest is only for testing and fuzzing"

[workspace.direct-dep-dups]
allow = [
]

[workspace.overlay]
features = ["failpoints", "fuzzing"]

# This is a list of test-only members. These are workspace members that do not form part of the main
# Aptos production codebase, and are only used to verify correctness and/or performance.
#
# *** IMPORTANT ***
#
# Published developer tools (e.g. Move compiler) ARE part of the production Aptos codebase.
# They should be listed in the root Cargo.toml's default-members, not here!
#
# Before adding a new crate to this list, ensure that it is *actually* test-only. If not, add it
# (or a crate that depends on it) to the root Cargo.toml's default-members list!
#
# For more, see the "Conditional compilation for tests" section in documentation/coding_guidelines.md.
[workspace.test-only]
members = [
    # Please keep this list in alphabetical order!

    "testcases",
    "aptos-e2e-tests-replay",
    "aptos-fuzz",
    "aptos-fuzzer",
    "aptos-keygen",
    "aptos-proptest-helpers",
    "aptos-retrier",
    "aptos-transactional-test-harness",
    "aptos-transaction-benchmarks",
    "aptos-writeset-generator",
    "diem-experimental-framework-releases",
    "executor-benchmark",
    "executor-test-helpers",
    "forge",
    "forge-cli",
    "generate-format",
    "language-e2e-tests",
    "language-e2e-testsuite",
    "memsocket",
    "move-examples",
    "smoke-test",
    "transaction-emitter",
    "x",
    "x-core",
    "x-lint",

    # Please keep this list in alphabetical order!
]

[workspace.move-to-aptos-deps]
# By default, all crates in the language directory are considered Move crates
# and are forbidden from depending on any Aptos crates.
#
# Adding a crate's name to this list will mark it as a Aptos crate so that the
# linter will not impose said restriction on it.
#
# Note: if your crate is indeed a Move crate and you are getting the linter
# yelling at you, you should redesign your crate and properly remove that
# dependency, instead of adding the crate to this list and silencing the lint.
aptos_crates_in_language = [
]
# A special set of aptos crates Move crates are allowed to depend on.
#
# You should not add new entries to this list unless you have a rare justifiable
# reason. (read: Just don't.)
#
# Particularly, please do not abuse this to silence the lint when it complains
# about Move crates depending on Aptos ones. Again, you should instead fix
# the design of your crate so it doesn't have to depend on Aptos.
exclude = [
    "aptos-workspace-hack",
]

# Interesting subsets of the workspace, These are used for generating and
# checking dependency summaries.

[subsets.lsr]
# The Aptos safety rules TCB.
root-members = [
    "safety-rules",
]

[subsets.lec]
# The Aptos execution correctness TCB.
root-members = [
    "execution-correctness",
]

[subsets.release]
# The Aptos release binaries
root-members = [
    "backup-cli",
    "db-bootstrapper",
    "aptos-genesis-tool",
    "aptos-node",
    "aptos-operational-tool",
    "execution-correctness",
    "safety-rules",
]

# ---
# Determinator rules
# ---

# CI-related files. TODO: maybe have separate rules for local and CI?
[[determinator.path-rule]]
globs = [".circleci/**/*", ".github/**/*", "codecov.yml"]
mark-changed = "all"

# Core devtools files.
[[determinator.path-rule]]
globs = [".config/nextest.toml", "scripts/dev_setup.sh", "x.toml"]
mark-changed = "all"

[[determinator.path-rule]]
# Ignore website and other ancillary files, and scripts not listed above.
globs = ["developer-docs-site/**/*", "documentation/**/*", "docker/**/*", "language/documentation/**/*", "specifications/**/*", "scripts/**/*", "terraform/**/*"]
mark-changed = []

[[determinator.path-rule]]
# A bunch of images that should be ignored, I guess.
globs = ["diem.png", ".assets/aptos_banner.png", ".assets/aptos.png", "storage/data.png"]
mark-changed = []

[[determinator.path-rule]]
# Ignore *.md documentation
globs = ["*.md"]
mark-changed = []

[[determinator.path-rule]]
# Required by get_stdlib_script_abis in transaction-builder-generator.
globs = ["aptos-move/framework/DPN/releases/artifacts/current/**/*"]
mark-changed = ["transaction-builder-generator"]
post-rule = "skip-rules"

[[determinator.package-rule]]
# x controls the build process, so if it changes, build everything.
on-affected = ["x"]
mark-changed = "all"
