[package]
name = "storage-service-server"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "The Aptos storage service (server-side)"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
bytes = "1.0.1"
futures = "0.3.12"
once_cell = "1.7.2"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["rt", "macros"], default-features = false }

bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
aptos-config = { path = "../../../config" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-metrics = { path = "../../../crates/aptos-metrics" }
aptos-types = { path = "../../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../../crates/aptos-workspace-hack" }
network = { path = "../../../network" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow = "1.0.52"
claim = "0.5.0"

aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-types = { path = "../../../types" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
storage-interface = { path = "../../../storage/storage-interface" }
