[package]
name = "aptos-api-types"
version = "0.0.1"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos API Types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
warp = { version = "0.3.2", features = ["default"] }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-resource-viewer = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

[dev-dependencies]
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
