[package]
name = "generate-format"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos core type checker to ensure compatibility"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
serde-reflection = "0.3.5"
serde_yaml = "0.8.17"
structopt = "0.3.21"

consensus = { path = "../../consensus", features=["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features=["fuzzing"] }
bcs = "0.1.2"
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto", features=["fuzzing"] }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive"}
aptos-types = { path = "../../types", features=["fuzzing"] }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
network = { path = "../../network" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features=["fuzzing"] }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
