[package]
name = "storage-interface"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos storage interface"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
itertools = "0.10.0"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
parking_lot = "0.11.1"

bcs = "0.1.2"
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-secure-net = { path = "../../secure/net" }
aptos-state-view = { path = "../state-view" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
scratchpad = { path = "../scratchpad" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

[features]
default = []
fuzzing = ["aptos-types/fuzzing"]
