[package]
name = "aptos-vm"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos VM runtime"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
once_cell = "1.7.2"
rayon = "1.5.0"
mirai-annotations = "1.10.1"
tracing = "0.1.16"

bcs = "0.1.2"
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-bytecode-utils = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-stdlib = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
framework =  { path = "../framework" }
serde_json = "1.0.64"
serde = { version = "1.0.124", default-features = false }
read-write-set-dynamic = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3"}

mvhashmap = { path = "../mvhashmap" }
aptos-parallel-executor = {path = "../parallel-executor" }

[dev-dependencies]
proptest = "1.0.0"

aptos-types = { path = "../../types", features = ["fuzzing"] }
diem-framework-releases = { path = "../framework/DPN/releases" }

[features]
default = []
mirai-contracts = []
fuzzing = ["move-binary-format/fuzzing","move-vm-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
