[package]
name = "aptos-types"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos core types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
aes-gcm = "0.8.0"
anyhow = "1.0.52"
bytes = "1.0.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
hex = "0.4.3"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
mirai-annotations = "1.10.1"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", default-features = false, optional = true }
rand = "0.8.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
serde_bytes = "0.11.5"
thiserror = "1.0.24"
tiny-keccak = { version = "2.0.2", default-features = false, features = ["sha3"] }

bcs = "0.1.2"
aptos-crypto = { path = "../crates/aptos-crypto", version = "0.0.3" }
aptos-crypto-derive = { path = "../crates/aptos-crypto-derive", version = "0.0.3" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", version = "0.0.3" }
move-read-write-set-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-workspace-hack = { version = "0.1", path = "../crates/aptos-workspace-hack" }

[dev-dependencies]
regex = "1.4.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = "1.0.64"

aptos-crypto = { path = "../crates/aptos-crypto", features = ["fuzzing"] }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features = ["fuzzing"]  }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "aptos-crypto/fuzzing", "move-core-types/fuzzing"]
