[package]
name = "aptos-validator-interface"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Defines interfaces between the aptos nodes and local move infrastructure"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
aptos-config = { path = "../../config" }
aptos-types = { path = "../../types" }
aptosdb = { path = "../../storage/aptosdb" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
storage-interface = { path = "../../storage/storage-interface" }
scratchpad = { path = "../../storage/scratchpad" }
aptos-state-view = { path = "../../storage/state-view" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
bcs = "0.1.2"
