[package]
name = "language-e2e-testsuite"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move language e2e tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
serde_json = "1.0.64"
hex = "0.4.3"
bcs = "0.1.2"
proptest = "1.0.0"

## Move dependencies
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-ir-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-bytecode-verifier = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
read-write-set = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

## Diem-Move dependencies
language-e2e-tests = { path = "../e2e-tests" }
aptos-keygen = { path = "../aptos-keygen" }
aptos-vm = { path = "../aptos-vm" }
diem-framework-releases = { path = "../framework/DPN/releases" }
aptos-parallel-executor = { path = "../parallel-executor" }
aptos-writeset-generator = { path = "../writeset-transaction-generator"}

## Other Diem dependencies
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-transaction-builder = { path = "../../sdk/transaction-builder"}
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }

[features]
default = ["aptos-transaction-builder/fuzzing"]
