[package]
name = "aptos-transaction-builder"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Generated transaction builders"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }

move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", version = "0.0.3" }
aptos-types = { path = "../../types", version = "0.0.3" }

proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "move-core-types/fuzzing"]
