[package]
name = "backup-cli"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.42"
byteorder = "1.4.3"
bytes = "1.0.1"
futures = "0.3.12"
hex = "0.4.3"
itertools = "0.10.0"
num_cpus = "1.13.0"
once_cell = "1.7.2"
pin-project = "1.0.5"
rand = "0.8.3"
regex = "1.5.5"
reqwest = { version = "0.11.2", features = ["stream"], default-features = false }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
toml = "0.5.8"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"
tokio-util = { version = "0.6.4", features = ["compat"] }

executor = { path = "../../../execution/executor" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers", optional = true }
executor-types = { path = "../../../execution/executor-types" }
aptos-jellyfish-merkle = { path = "../../jellyfish-merkle" }
bcs = "0.1.2"
aptos-config = { path = "../../../config" }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-secure-push-metrics = { path = "../../../secure/push-metrics" }
aptos-temppath = { path = "../../../crates/aptos-temppath" }
aptos-types = { path = "../../../types" }
aptos-vm = { path = "../../../aptos-move/aptos-vm" }
aptos-workspace-hack = { version = "0.1", path = "../../../crates/aptos-workspace-hack" }
aptosdb = { path = "../../aptosdb" }
storage-interface = { path = "../../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
warp = "0.3.2"

backup-service = { path = "../backup-service" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
aptosdb = { path = "../../aptosdb", features = ["fuzzing"] }
aptos-config = { path = "../../../config" }
aptos-proptest-helpers = { path = "../../../crates/aptos-proptest-helpers" }
storage-interface = { path = "../../storage-interface" }

[features]
fuzzing = ["aptosdb/fuzzing"]
