[package]
name = "smoke-test"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos end to end tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.42"
bcs = "0.1.2"
proptest = "1.0.0"
tokio = { version = "1.8.1", features = ["full"] }
walkdir = "2.3.1"
reqwest = { version = "0.11.2", features = ["json"] }

aptos-framework-releases = { path = "../../aptos-move/framework/aptos-framework/releases" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
diem-experimental-framework-releases = { path = "../../aptos-move/framework/experimental/releases" }
framework =  { path = "../../aptos-move/framework" }
diem-framework-releases = { path = "../../aptos-move/framework/DPN/releases" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
forge = { path = "../forge" }
move-command-line-common = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-ir-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-stdlib = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-package = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }


[dev-dependencies]
base64 = "0.13.0"
hex = "0.4.3"
once_cell = "1.7.2"
rand = "0.8.3"
regex = "1.5.5"
serde_yaml = "0.8.17"
futures = "0.3.12"

backup-cli = { path = "../../storage/backup/backup-cli" }
debug-interface = { path = "../../crates/debug-interface" }
generate-key = { path = "../../config/generate-key" }
aptos-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
aptos-global-constants = { path = "../../config/global-constants" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-management = { path = "../../config/management", features = ["testing"] }
aptos-operational-tool = {path = "../../config/management/operational", features = ["testing"] }
aptos-secure-storage = { path = "../../secure/storage", features = ["testing"] }
aptos-time-service = { path = "../../crates/aptos-time-service", features = ["testing"] }
aptos-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
aptos-writeset-generator = { path = "../../aptos-move/writeset-transaction-generator" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }

[[test]]
name = "forge"
harness = false

[[test]]
name = "forge-nft"
harness = false

[[test]]
name = "forge-aptos"
harness = false
