[package]
name = "transaction-builder-generator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction-builder"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
heck = "0.3.2"
regex = "1.5.5"
structopt = "0.3.21"
textwrap = "0.13.4"
serde_yaml = "0.8.17"

aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
serde-reflection = "0.3.5"
serde-generate = "0.20.6"
bcs = "0.1.2"

[dev-dependencies]
tempfile = "3.2.0"
which = "4.0.2"

[features]
default = []

[[bin]]
name = "generate-transaction-builders"
path = "src/generate.rs"
test = false
