[package]
name = "executor"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos executor"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
rayon = "1.5.0"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }

consensus-types = { path = "../../consensus/consensus-types"}
executor-types = { path = "../executor-types" }
bcs = "0.1.2"
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-secure-net = { path = "../../secure/net" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.3"

diem-framework-releases = { path = "../../aptos-move/framework/DPN/releases" }
executor-test-helpers = { path = "../executor-test-helpers" }
aptos-config = { path = "../../config" }
aptos-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptosdb = { path = "../../storage/aptosdb" }
move-ir-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
storage-interface = { path = "../../storage/storage-interface", features=["fuzzing"] }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
vm-genesis = { path = "../../aptos-move/vm-genesis" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "aptos-crypto/fuzzing", "aptos-types/fuzzing", "proptest", "storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "aptos-vm/failpoints"]
