[package]
name = "aptos-framework-releases"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Framework Releases"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false


[dependencies]
move-command-line-common = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-crypto = { path = "../../../../crates/aptos-crypto" }
aptos-types = { path = "../../../../types" }
aptos-workspace-hack = { path = "../../../../crates/aptos-workspace-hack" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
framework-releases = { path = "../../releases" }

anyhow = "1.0.52"
include_dir = "0.6.0"
bcs = "0.1.2"
once_cell = "1.7.2"
