[package]
name = "df-cli"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "CLI frontend for the Move compiler and VM (with Diem Framework)"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
structopt = "0.3.21"

aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-cli = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-vm = { path = "../aptos-vm" }
diem-framework-releases = { path = "../framework/DPN/releases" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[bin]]
name = "df-cli"
path = "src/main.rs"

[[test]]
name = "cli_testsuite"
harness = false
