[package]
name = "aptosdb"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos database"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
arc-swap = "1.2.0"
byteorder = "1.4.3"
itertools = "0.10.0"
once_cell = "1.7.2"
num-derive = "0.3.3"
num-traits = "0.2.14"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = "1.0.124"
thiserror = "1.0.24"

accumulator = { path = "../accumulator" }
bcs = "0.1.2"
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-jellyfish-merkle = { path = "../jellyfish-merkle" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers", optional = true }
aptos-temppath = { path = "../../crates/aptos-temppath", optional = true }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
executor-types = { path = "../../execution/executor-types", optional = true }
move-core-types = {git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3"}

num-variants = { path = "../../crates/num-variants" }
schemadb = { path = "../schemadb" }
scratchpad = { path = "../scratchpad", optional = true }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.8.3"

aptos-jellyfish-merkle = { path = "../jellyfish-merkle", features = ["fuzzing"] }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
executor-types = { path = "../../execution/executor-types", features = ["fuzzing"] }
schemadb = { path = "../schemadb", features = ["fuzzing"] }
scratchpad = { path = "../scratchpad", features = ["fuzzing"] }

[features]
default = []
aptossum = []
fuzzing = ["proptest", "proptest-derive", "aptos-proptest-helpers", "aptos-temppath", "aptos-crypto/fuzzing", "aptos-jellyfish-merkle/fuzzing", "aptos-types/fuzzing", "executor-types/fuzzing", "schemadb/fuzzing", "scratchpad/fuzzing"]
