[package]
name = "aptos-transactional-test-harness"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Transactional testing framework for Move"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
once_cell = "1.7.2"
anyhow = "1.0.52"
structopt = "0.3.21"
bcs = "0.1.2"
hex = "0.4.3"

# Move dependencies
move-transactional-test-runner = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-command-line-common = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

# Diem-Move dependencies
language-e2e-tests = { path = "../e2e-tests" }
aptos-vm =  { path = "../aptos-vm" }
vm-genesis= { path = "../vm-genesis" }
framework =  { path = "../framework" }
aptos-keygen = { path = "../aptos-keygen" }

# Other Diem dependencies
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
