[package]
name = "language-e2e-tests"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move language e2e testing framework"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.52"
goldenfile = "1.1.0"
bcs = "0.1.2"
once_cell = "1.7.2"
rand = "0.8.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }

## Move dependencies
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-ir-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
read-write-set = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-command-line-common = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }

## Diem-Move dependencies
aptos-writeset-generator = { path = "../writeset-transaction-generator" }
vm-genesis = { path = "../vm-genesis" }
aptos-vm = { path = "../aptos-vm" }
aptos-keygen = { path = "../aptos-keygen" }
diem-framework-releases = { path = "../framework/DPN/releases" }

## Other Diem Dependencies
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-config = { path = "../../config" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }
