[package]
name = "aptos-rest-client"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos REST client"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[features]
default = ["dpn"]
dpn = []

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
hex = "0.4.3"
reqwest = { version = "0.11.2", features = ["json", "cookies"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.8.1", features = ["full"] }
url = "2.2.2"

aptos-api-types = { path = "../../api/types" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { version = "0.1", path = "../aptos-workspace-hack" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
