[package]
name = "aptos-sdk"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "The Official Aptos SDK"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
bcs = "0.1"
rand_core = "0.6.2"
serde = { version = "1.0.124", features = ["derive"] }

aptos-crypto = { path = "../crates/aptos-crypto", version = "0.0.3" }
aptos-types = { path = "../types", version = "0.0.3"}
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", version = "0.0.3" }
aptos-transaction-builder = { path = "./transaction-builder", version = "0.0.3" }
aptos-workspace-hack = { version = "0.1", path = "../crates/aptos-workspace-hack" }
