[package]
name = "aptos-fuzzer"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos fuzzer"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# common dependencies
[dependencies]
anyhow = "1.0.52"
byteorder = { version = "1.4.3", default-features = false }
hex = "0.4.3"
once_cell = "1.7.2"
proptest = { version = "1.0.0", default-features = false }
proptest-derive = { version = "0.3.0", default-features = false }
rusty-fork = { version = "0.3.0", default-features = false }
serde_json = "1.0.64"
sha-1 = { version = "0.9.4", default-features = false }
structopt = "0.3.21"
rand = "0.8.3"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

bcs = "0.1.2"
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-workspace-hack = { version = "0.1", path = "../../crates/aptos-workspace-hack" }

# List out modules with data structures being fuzzed here.
accumulator = { path = "../../storage/accumulator", features = ["fuzzing"] }
consensus = { path = "../../consensus", features = ["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features = ["fuzzing"] }
executor = { path = "../../execution/executor", features = ["fuzzing"] }
executor-types = { path = "../../execution/executor-types", features = ["fuzzing"] }
language-e2e-tests = { path = "../../aptos-move/e2e-tests" }
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"]}
aptos-jellyfish-merkle = { path = "../../storage/jellyfish-merkle", features = ["fuzzing"] }
aptos-mempool = { path = "../../mempool" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
aptosdb = { path = "../../storage/aptosdb", features = ["fuzzing"] }
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features = ["fuzzing"] }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features = ["fuzzing"] }
network = { path = "../../network", features = ["fuzzing"] }
safety-rules = { path = "../../consensus/safety-rules", features = ["fuzzing", "testing"]  }
scratchpad = { path = "../../storage/scratchpad", features = ["fuzzing"]}
state-sync-v1 = { path = "../../state-sync/state-sync-v1", features = ["fuzzing", "aptosdb"]  }
storage-interface = { path = "../../storage/storage-interface" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3", features = ["fuzzing"] }

[dev-dependencies]
rusty-fork = "0.3.0"
stats_alloc = "0.1.8"

datatest-stable = "0.1.1"

[[test]]
harness = false
name = "artifacts"
