[package]
name = "aptos-writeset-generator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.3"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
once_cell = "1.7.2"

move-bytecode-verifier = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types" }
diem-framework-releases = { path = "../framework/DPN/releases" }
framework =  { path = "../framework" }
move-compiler = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
bcs = "0.1.2"
aptos-state-view = { path = "../../storage/state-view" }
aptos-transaction-replay = { path = "../transaction-replay" }
aptosdb = { path = "../../storage/aptosdb" }
aptos-vm = { path = "../aptos-vm" }
move-binary-format = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3"}
move-vm-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-core-types = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
move-vm-test-utils = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
read-write-set = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
