[package]
name = "aptos-transaction-benchmarks"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction benchmarks"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
criterion = "0.3.4"
proptest = "1.0.0"
criterion-cpu-time = "0.1.0"

aptos-types = { path = "../../types", features = ["fuzzing"] }
language-e2e-tests = { path = "../e2e-tests" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptos-crypto = { path = "../../crates/aptos-crypto" }

read-write-set = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
read-write-set-dynamic = { git = "https://github.com/diem/move", rev = "8a260b82dda8175a98ea848fab5adcce467585b3" }
aptos-vm = { path = "../aptos-vm" }
diem-framework-releases = { path = "../framework/DPN/releases" }

[[bench]]
name = "transaction_benches"
harness = false
